Build a complete, fully functional, production-quality sports betting web app exactly like SportyBet Ghana, in a single file src/App.jsx, mobile-first, using React + Tailwind CSS classes, no backend, all state in useState + localStorage.

PROJECT NAME: BetX Ghana - Sportsbook Where Customers Stake Bets (Demo Wallet - No Real Payment Gateway, No WhatsApp)

BRANDING: Background #121212, card #2a2a2a, card active #383838, border #333, black #0f0f0f, primary red #e00000, red dark #a80000, header gradient 135deg #e00000 to #a80000, odds yellow #ffeb3b, selected red #e00000 white text, green live #00e676, font Arial, rounded 5px to 20px.

GLOBAL STATE: matches array, selectedMatch null|object, marketTab string default "1X2", bets array {id: `${matchId}-${market}-${selection}`, matchId, game: "Home vs Away", league, market, selection, odd}, betType "Single"|"Multiple"|"System" default "Multiple", stake number default 10 GH₵ min 0.20, tickets array persisted localStorage "betx_tickets" {id: "BX"+Date.now, date, stake, totalOdds, potentialWin, status: "Open"|"Won"|"Lost", picks: bets[], cashout: stake*0.85}, user {name:"popki", balance:50} persisted "betx_user", tab "home"|"az"|"open"|"me" default "home", filter "all"|"live"|"upcoming" default "all", search string, loading, error, lastUpdated, viewTicket null|ticket.

HEADER sticky top 0 z50 background gradient #e00000 to #a80000 padding 13px 15px flex justify-between: Left Logo SportyBet italic bold 22px + badge GHANA 9px, Right Search input, Refresh button, Balance pill rgba(0,0,0,0.3) GH₵ {balance.toFixed(2)}.

CONNECTION BAR #171717 borderBottom #252525 padding 8px 12px font 10px color green #62e36b if connected else red #ff6b6b: "● API-Football connected" or "● Mock data - add API key" + Updated {time} + Live {count}.

HOME PAGE: Search bar #242424 border #363636 radius 7px padding 11px 13px width 100% placeholder "Search team or league..." onChange setSearch. Sports pills scroll: All Sports, Football active red, Live red dot, Basketball, Tennis, Volleyball, Hockey, Handball, Esports, Virtuals - active #e00000 white, inactive #292929 #aaa, 8px 13px radius 18px 11px bold onClick filter. Sub-pills TODAY'S FOOTBALL, FOOTBALL IN NEXT 3 HOURS. Featured Virtuals card NFO vs LEE. Table header grid 1fr 50px 50px 50px background black #000 #777 10px: "Tap row for markets ›" + 1 X 2. Match List each row background #202020 marginBottom 5px borderBottom #101010: Top bar #292929 padding 8px 11px flex justify-between: badge LIVE BOOST red or HOT orange, time, league, country left 10px #aaa, score right green #00e676 if live else gray #666 + ›, onClick setSelectedMatch(match) setMarketTab("1X2"). Middle teams grid 1fr 40px 1fr align center padding 11px 10px 7px cursor pointer: Home logo 28px + name 12px 600 left, VS center #777 10px, Away name + logo right. Bottom odds grid 3 cols gap 5px padding 3px 10px 11px: buttons Home Draw Away with odd value, disabled #242424 #666 if no odd else #383838 #ffeb3b, selected #e00000 white border #ff3333, onClick stopPropagation addBet. Footer oddsSource 8px #666 right.

MATCH DETAIL PAGE when selectedMatch != null: Header red #e00000 sticky top 0 Back button left onClick setSelectedMatch(null) center title home vs away. Top info #1a1a1a padding 15px center: league country time 11px #999, teams 18px bold vs gray, live green LIVE minute score, stats row Possession Shots 11px #888, tags LIVE BOOST red, Stats, Live. Market tabs scrollable overflow auto background black borderBottom #222 font 11px: tabs from Object.keys(match.markets) like 1X2, Over/Under, Double Chance, 1st Half O/U, Handicap, Next Goal, Home, Away - padding 12px 14px nowrap active white borderBottom 2px #e00000 bg #1a1a1a inactive #888 onClick setMarketTab. Market content grid 2 cols gap 8px padding 12px: each option button left selection name right odd, style same, selected red, onClick addBet. Insurance section Flex, 1UP, EarlyGoals checkboxes 10px.

BETSLIP fixed bottom 58px when bets.length>0 background #181818 borderTop 2px #e00000 padding 10px z55 shadow: Top flex justify between BET SLIP (count) bold Clear red. Middle maxHeight 70px overflowY auto marginTop 6px list picks 10px #bbb "Game • selection @ odd". Bottom grid 75px 1fr 1fr gap 7px marginTop 8px: Stake input #050505 #444 radius5 padding9, Total Odds box #242424 radius5 padding8 label TOTAL ODDS 9px #777 value #ffeb3b bold totalOdds.toFixed(2), Place Bet button #e00000 white bold. Extra pills Single|Multiple|System active white black inactive #292929 #aaa. Floating bubble 48px circle #e00000 bottom 70px right 16px count white bold.

OPEN BETS PAGE tab open: Top tabs Open Bets (count) and Bet History background white radius20 padding3 font12 active black white inactive #888. Filters All|Cashout Available|Live Games All active red #e00000 padding5px10px radius15 others #222 #aaa. Ticket list each ticket background #202020 border #303030 radius9 padding12 marginTop10 onClick setViewTicket: Top flex justify between ID date 11px status badge orange #754d00 #ffd76a radius15 padding3px8px 9px Won green Lost red Open orange. Middle first game + more Details 11px. Bottom flex justify between Stake GHS win GHS yellow. Buttons row gap6 marginTop8 Remix Bet red #e00000 padding6px12px radius4 10px, Cashout GHS (stake*0.85) #222, Edit Bet, SIM.

TICKET DETAILS PAGE when viewTicket !=null: white bg #fff black minHeight100vh Header red #e00000 white padding12px flex justify between Back onClick setViewTicket(null) Ticket Details bold. Content padding15px font13px Total Stake, Total Return, Odds, ID, Date, selections list padding8px0 borderBottom1px #eee Market Pick FT Score Bet Result, buttons Remix Bet 100% marginTop15px bg #e00000 white padding12px border none radius6px, Delete Ticket black white.

A-Z MENU PAGE tab az white bg black text minHeight70vh padding10px Top search bar red #e00000 padding8px radius20px flex input placeholder Teams Players Leagues ID border none transparent white outline none flex1. Below flex: Left 120px bg #f5f5f5 Popular Sports Football active left border3px #e00000 bg white vFootball Basketball Tennis etc padding12px. Right flex1 padding10px font13px Today's Football leagues England Premier League Spain LaLiga Bundesliga Italy Serie A Ghana Premier League each padding10px0 borderBottom1px #eee with ›.

ME PAGE tab me padding15px Top black card #222 padding20px radius12px center: Avatar 50px circle #e00000 P, name popki arrow, Loyalty Tier 10px #888, Total Balance GH₵ balance eye icon 28px bold yellow #ffeb3b marginTop8px, grid2 cols gap10px marginTop15px Deposit green #00c853 white padding12px radius6px demo only, Withdraw dark #333 white. Sporty Loyalty Earn Rewards bar. List Sports Bet History >, Transaction Records >, Gifts (2) Lucky Wheel (0) >, My Social Create >, Daily Streak 16 >, Customer Service Online 24/7 >, Notification Center >, Rate Our App >, How to play >, Share an Idea >, Update App >, Log Out red center. Footer Paybill *711*222# reference VISA MTN Tigo 18+ License 0000237.

BOTTOM NAV fixed bottom0 left0 right0 height58px bg #111 borderTop1px #292929 display grid 4 cols z60: Home ⚽, A-Z 📊, Open Bets 🧾 with badge red if open count>0, Me 👤 with balance, border none transparent color active #e00000 inactive #777 font10px icon18px marginBottom2px active bold onClick setTab.

FUNCTIONS: CONFIG with API_BASE https://v3.football.api-sports.io API_KEY YOUR_API_FOOTBALL_KEY LEAGUES array ids 39,140,2,78,135,61,233 REFRESH_MS 30000, apiFootball(endpoint) throws if NO_KEY, formatTime, isLiveFixture, normalizeFixture, fetchFixtures today date, fetchFixtureOdds fixtureId with Match Winner and Goals Over/Under parsing, fetchMatchesFromAPI try fetchFixtures then odds for first 30, map to app format with markets {1X2, Over/Under, Double Chance, 1st Half O/U, Handicap, Next Goal}, if NO_KEY return mock 5 matches Coventry vs QPR live HT 0-0 odds 1.32/4.8/12 etc, loadMatches sets matches lastUpdated error loading refreshing, useEffect load + interval 30s, localStorage tickets user, totalOdds useMemo product, possibleWin, filteredMatches useMemo filter live upcoming search, addBet toggles and removes same matchId other picks, placePaperTicket validates stake>0 <=balance creates ticket BX+timestamp save deduct balance clear bets switch tab bets, components TeamLogo fallback ⚽ circle, OddsButton disabled no odd selected red unselected dark yellow, NavButton, Loading ⚽ Loading real football data..., EmptyMatches No matches.

PERSISTENCE localStorage betx_tickets betx_user. MOCK 5 matches. ERROR banner #281414 border #7a2525 radius8 margin12 padding14. RESPONSIVE mobile-first single column. KEY FIX onClick whole match row navigates to detail page, odds buttons add to betslip instantly red. All buttons work no dead. React hooks only no backend no WhatsApp no real payment demo only 18+ footer.
